### ISSUE TITLE
Exited (1) when I launch the container

### ISSUE THREAD

**Issue by weado** [voxic/ha-editor#4]
Hello, 
I would like to install Ha Editor with the simple howto, but my container doesn't want to start.

I don't understand what is my problem with ha-editor.

`CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                     PORTS               NAMES
032b8f636c9c        voxic/ha-editor                       "node app"               4 minutes ago       Exited (1) 4 minutes ago                       competent_rosalind
`

When I use the `-it` command, that is the message from docker : `standard_init_linux.go:211: exec user process caused "exec format error"`

**Comment by weado** [comment]
Nobody can help me ?

**Comment by voxic** [comment]
Hi, I will have a look at this tonight.

**Comment by voxic** [comment]
Hi 

This error seems to be related to the architecture you are trying to run the image on.

> That error usually means you're trying to run this amd64 image on a non-amd64 host (such as 32-bit or ARM).
- https://github.com/docker-library/mysql/issues/228

On what kind of system are you trying to run the image?

**Comment by weado** [comment]
I tried to use this image on amd64 platform (Debian Buster).

**Comment by voxic** [comment]
Issue is related to Docker usage.
